from pydantic import BaseModel
from typing import List, Optional, Dict, Any


# ── Stage 1 model ─────────────────────────────────────────────────────────
class GoalAnalysis(BaseModel):
    goal: str
    domain: str
    complexity: str          # low | medium | high
    subtasks: List[str]      # plain string list (high-level)
    required_roles: List[str]


# ── Stage 3 models ─────────────────────────────────────────────────────────
class AgentRole(BaseModel):
    """Represents a single AI agent role within the organization."""
    name: str
    description: str
    responsibilities: List[str]


class Subtask(BaseModel):
    """A detailed subtask assigned to a specific agent role."""
    title: str
    description: str
    assigned_role: str


class OrganizationPlan(BaseModel):
    """The full organization plan generated by the Organization Builder."""
    roles: List[AgentRole]
    subtasks: List[Subtask]
    team_size: int


# ── Stage 4 Execution models ───────────────────────────────────────────────
class TaskExecutionResult(BaseModel):
    """Result of executing a single subtask by an assigned agent role."""
    subtask_title: str
    assigned_role: str
    status: str            # completed | failed | in_progress
    deliverable: str
    output_summary: str
    timestamp: str
    validation_status: str = "PASS"             # PASS | FAIL
    quality_score: float = 98.5                 # 0.0 - 100.0
    retry_count: int = 0                        # Number of retry/replace iterations
    critic_notes: str = "Validated by Critic Agent: Passed requirements check."
    validation_action: str = "APPROVED"         # APPROVED | RETRIED_AND_REPLACED


class ExecutionReport(BaseModel):
    """Full execution report across all subtasks in the organization plan."""
    project_id: str
    status: str            # completed | partial_failure | in_progress
    total_tasks: int
    completed_tasks: int
    results: List[TaskExecutionResult]
    shared_project_state: Dict[str, Any] = {}
    validation_summary: Dict[str, Any] = {
        "total_passed": 0,
        "total_retried": 0,
        "critic_status": "PASS",
    }


# ── Stage 5 Conflict & Synthesis models ─────────────────────────────────────
class ProjectConflict(BaseModel):
    """Represents a detected collaboration conflict between agent subtasks/roles."""
    title: str
    description: str
    impact_level: str      # high | medium | low
    affected_roles: List[str]
    resolution_strategy: str
    status: str            # resolved | open


class MasterProjectPlan(BaseModel):
    """Synthesized master project execution plan combining all agent deliverables."""
    project_id: str
    executive_summary: str
    domain: str
    complexity: str
    total_agents: int
    total_tasks: int
    conflicts_resolved: List[ProjectConflict]
    deliverables_summary: List[Dict[str, Any]]
    final_roadmap: List[str]
    created_at: str
    reflection_learning: Dict[str, Any] = {
        "key_learnings": [],
        "system_reflection": "",
        "feedback_loop_status": "COMPLETED",
    }


# ── Stage 6 Analytics & Metrics models ─────────────────────────────────────
class AgentPerformanceMetric(BaseModel):
    """Performance & workload metric for an individual agent role."""
    role_name: str
    tasks_completed: int
    load_percentage: float
    efficiency_score: float


class ProjectAnalyticsReport(BaseModel):
    """Real-time system health score, workload distribution & operational metrics."""
    project_id: str
    health_score: int          # 0 - 100
    readiness_score: int       # 0 - 100
    risk_index: str            # Low | Medium | High
    completion_rate: float     # Percentage (0 - 100%)
    agent_metrics: List[AgentPerformanceMetric]
    recommendations: List[str]
    calculated_at: str
    reflection_metrics: Dict[str, Any] = {
        "validation_pass_rate": 100.0,
        "learning_score": 96.5,
        "feedback_iterations": 1,
    }
# ── LangGraph Coordination Models ──────────────────────────────────────────
class ProposalModel(BaseModel):
    role: str
    proposal: str
    confidence: float
    reasoning: str
    status: str = "success"  # success | failed


class TelemetryLogModel(BaseModel):
    node: str
    role: Optional[str] = None
    status: str              # success | retry | failed
    timestamp: str


class NegotiatorResultModel(BaseModel):
    winner: Dict[str, Any]
    total_proposals: int
    successful_proposals: int
    note: Optional[str] = None


class GraphExecutionResponse(BaseModel):
    goal: str
    roles: List[str]
    proposals: List[ProposalModel]
    winner: Dict[str, Any]
    logs: List[TelemetryLogModel]
    output: Dict[str, Any]
